const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');const {chromium}=require('playwright');
fs.mkdirSync('output',{recursive:true});
const root=path.resolve(__dirname,'../site');
const server=http.createServer((req,res)=>{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root)){res.statusCode=403;return res.end();}if(req.url.startsWith('/fixture')){let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script type="module" src="host.js[^"]*"><\/script>/,'');res.setHeader('Content-Type','text/html');return res.end(html);}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.png')?'image/png':'text/plain');let data=fs.readFileSync(file);if(file.endsWith('addin.js'))data=data.toString().replace(/^import .*;$/m,'');res.end(data);}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||(process.platform==='win32'?'C:/Program Files/Google/Chrome/Application/chrome.exe':undefined)});try{const page=await browser.newPage({viewport:{width:420,height:820}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${port}/fixture`);await page.waitForFunction(()=>!!window.__lesson);await page.evaluate(()=>{const L=window.__lesson,S=L.S;S.role='student';S.joined=true;S.connected=true;S.me={name:'Student',key:'me'};S.deck={title:'Test lesson',slides:[{id:'q',type:'short',graded:false,title:'Explain your idea'}]};S.deckLoaded=true;S.myAns={q:'My own response'};S.live={code:'ABCDE',slide:0,presenting:false,open:false,tierNames:['A','B','C'],tiers:{}};L.render(true);});assert((await page.locator('#app').innerText()).includes('Waiting for your teacher'));await page.evaluate(()=>{const L=window.__lesson;Object.assign(L.S.live,{presenting:true,open:true,reveal:true,revealKey:{id:'q',key:{accept:['SECRET KEY']}},summary:{rows:[{label:'OTHER RESPONSE',n:1}]}});L.render(true);});const studentText=await page.locator('#app').innerText();assert(!studentText.includes('SECRET KEY'));assert(!studentText.includes('OTHER RESPONSE'));assert.equal(await page.locator('input[id^="s-ans"]').inputValue(),'My own response');await page.screenshot({path:'output/student-nour-preview.png'});
await page.evaluate(async()=>{const L=window.__lesson,S=L.S;S.role='teacher';S.live={slide:0,code:'ABCDE',open:false,presenting:false,reveal:false,sessionId:'s',tierNames:['A','B','C'],thresholds:[50,80]};S.keys={};S.respRaw={};S.peers=[];S.db={doc:()=>({set:async()=>{}})};window.EMBED=await import('/addin/taskpane.js');L.render(true);});await page.getByRole('button',{name:'+ Add interaction',exact:true}).click();await page.getByRole('button',{name:/Short answer/}).click();await page.getByLabel('Your question').fill('What did you learn?');assert.equal(await page.getByLabel('Interaction type').inputValue(),'short');assert.equal(await page.getByText('Accepted answers (one per line)').count(),0);assert.equal(await page.getByText('Import slides').count(),0);assert.equal(await page.getByRole('button',{name:'Add to presentation',exact:true}).count(),1);await page.screenshot({path:'output/nour-panel-preview.png'});await page.route('https://appsforoffice.microsoft.com/**',route=>route.fulfill({contentType:'text/javascript',body:''}));
await page.evaluate(async()=>{const L=window.__lesson,S=L.S;S.liveLoaded=true;S.deckLoaded=true;S.deck={title:'Test',slides:[{id:'q',type:'poll',title:'Choose',options:['A','B'],resultsMode:'click',timerSeconds:1}]};S.live={slide:0,code:'ABCDE',presenting:false,open:false,reveal:false,sessionId:'s',tierNames:['A','B','C']};S.keys={};S.respRaw={};window.officeEvents={};window.Office={onReady:async()=>({host:'PowerPoint'}),EventType:{ActiveViewChanged:'active',DocumentSelectionChanged:'selection'},context:{document:{settings:{get:key=>key==='liveLesson'?{mode:'slide',id:'q'}:key==='liveLessonManaged'?true:null},getActiveViewAsync:cb=>cb({status:'succeeded',value:'edit'}),addHandlerAsync:(type,cb)=>window.officeEvents[type]=cb}}};window.EMBED=await import('/addin/addin.js');await window.EMBED.init();L.render(true);});
assert((await page.locator('#app').innerText()).includes('Slide preview'));assert.equal(await page.locator('.bars').count(),0);
await page.evaluate(()=>window.officeEvents.active({activeView:'read'}));await page.waitForFunction(()=>window.__lesson.S.live.presenting&&window.__lesson.S.live.open);assert.equal(await page.locator('.bars').count(),0);
await page.getByRole('button',{name:'Show results',exact:true}).click();assert.equal(await page.locator('.bars').count(),1);assert.equal(await page.evaluate(()=>window.__lesson.S.live.reveal),false);assert.equal(await page.evaluate(()=>window.__lesson.S.live.summary),null);
await page.waitForFunction(()=>!window.__lesson.S.live.open);await page.getByRole("button",{name:"Reopen answers",exact:true}).click();assert.equal(await page.evaluate(()=>window.__lesson.acceptingAnswers(window.__lesson.S.live)),true);await page.evaluate(()=>window.officeEvents.active({activeView:'edit'}));assert.equal(await page.evaluate(()=>window.__lesson.S.live.presenting),false);
await page.evaluate(async()=>{window.EMBED=await import('/addin/taskpane.js');window.__lesson.render(true);});await page.getByRole('button',{name:'Interactions',exact:true}).click();await page.getByRole('button',{name:'+ Add interaction',exact:true}).click();await page.getByRole('button',{name:/^Quiz/}).click();await page.getByLabel('Allow multiple answers').check();assert.equal(await page.locator('input[name="correct"][type="checkbox"]').count(),3);await page.locator('input[name="correct"]').nth(0).check();await page.locator('input[name="correct"]').nth(1).check();
await page.getByLabel('Upload question picture').setInputFiles({name:'picture.png',mimeType:'image/png',buffer:fs.readFileSync(path.join(root,'assets/nour-icon-64.png'))});await page.locator('.question-picture img').waitFor();assert.equal(await page.locator('.question-picture img').count(),1);const pictureData=await page.locator('.question-picture img').getAttribute('src');
await page.getByRole('button',{name:'Cancel',exact:true}).click();
for (const type of ['Poll','Quiz','Select all','True or false','Rating','Open response','Number','Short answer','Group tasks']) {
 await page.getByRole('button',{name:'+ Add interaction',exact:true}).click();await page.getByRole('button',{name:new RegExp('^'+type)}).click();assert.equal(await page.getByLabel('Upload question picture').count(),1);await page.getByRole('button',{name:'Cancel',exact:true}).click();
}

await page.evaluate(async data=>{const L=window.__lesson,S=L.S;const sl={id:'q',type:'mcq',title:'Picture question',options:['A','B']};await L.uploadPicture(sl,new File([await (await fetch(data)).blob()],'picture.jpg',{type:'image/jpeg'}));S.deck={title:'Test',slides:[sl]};S.role='student';S.keys={};S.myAns={};S.answerTimes={};S.live={slide:0,presenting:true,open:true,roundId:'r',startedAt:Date.now()-1000,sessionId:'s',tierNames:['A','B','C'],tiers:{}};S.room={presence:async data=>window.sentResponse=data};L.render(true);},pictureData);assert.equal(await page.locator('.question-picture img').count(),1);await page.locator('.opt').first().click();assert.equal(await page.evaluate(()=>window.sentResponse),undefined);await page.getByRole('button',{name:'Send',exact:true}).click();const sent=await page.evaluate(()=>window.sentResponse);assert.equal(sent.answerTimes.q.round,'r');assert(sent.answerTimes.q.elapsedMs>=0);
await page.evaluate(async()=>{const L=window.__lesson,S=L.S;S.role='teacher';S.deck={title:'Quiz',slides:[{id:'q',type:'mcq',title:'Quiz',options:['A','B'],quiz:true,resultsMode:'immediate',points:1}]};S.keys={q:{correct:0}};S.peers=[];S.live={slide:0,presenting:true,open:false,reveal:true,resultsVisible:true,sessionId:'s',overrides:{},tiers:{},rounds:{q:{id:'r',seconds:30}},tierNames:['A','B','C'],thresholds:[50,80]};S.respRaw={a:{sid:'s',name:'Sara Fast',ans:{q:0},answerTimes:{q:{round:'r',elapsedMs:1000}}},b:{sid:'s',name:'Bob Slow',ans:{q:0},answerTimes:{q:{round:'r',elapsedMs:20000}}},c:{sid:'s',name:'Third Person',ans:{q:1},answerTimes:{q:{round:'r',elapsedMs:0}}}};window.EMBED=await import('/addin/addin.js');window.officeEvents.active({activeView:'read'});L.render(true);});assert((await page.locator('.leaderboard li').first().innerText()).includes('Sara Fast'));await page.setViewportSize({width:1000,height:650});await page.screenshot({path:'output/quiz-leaderboard.png'});
await page.evaluate(()=>{const L=window.__lesson;L.S.deck.slides[0].type='poll';L.S.keys={};L.render(true);});assert((await page.locator('.bars .bar').first().innerText()).includes('67%'));assert.equal(await page.locator('.voter-chips').first().locator('.pill').count(),2);assert((await page.locator('.voter-chips').first().innerText()).includes('SF'));await page.screenshot({path:'output/poll-participants.png'});
await page.evaluate(()=>{const L=window.__lesson;L.S.live.code='K7M2Q';L.render(true);});assert.equal(await page.locator('.joinbar .qr, .joincard .qr').count()>0,true);assert.equal(await page.evaluate(()=>window.__lesson.joinUrl('K7M2Q').endsWith('/?code=K7M2Q')||window.__lesson.joinUrl('K7M2Q').includes('code=K7M2Q')),true);
await page.evaluate(()=>{const L=window.__lesson,S=L.S;window.EMBED=null;S.role='student';S.joined=true;S.myAns={};S.draft={};S.room={presence:async()=>{}};S.me={name:'Test',key:'test'};S.live={slide:0,presenting:true,open:true,roundId:'send-round',sessionId:'s',tierNames:['A','B','C']};S.deck={slides:[{id:'send-q',type:'multi',title:'Select two',options:['First','Second','Third']}]};L.render(true);});
await page.getByRole('button',{name:/First/}).click();await page.getByRole('button',{name:/Second/}).click();assert.equal(await page.evaluate(()=>window.__lesson.S.myAns['send-q']),undefined);await page.getByRole('button',{name:'Send',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.__lesson.S.myAns['send-q']),[0,1]);assert((await page.locator('#app').innerText()).includes('Answer sent!'));
assert.deepEqual(errors,[]);console.log('PASS: real browser bootstrap, waiting screen, own-response-only privacy despite legacy payload, no required short-answer key, single-question form, no import, Office edit/read transition, results on click, timer closes answers, multi-answer choices, image upload/display, response timing, ranked leaderboard, poll percentages/initials, join QR on the live slide');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});


