const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');const {chromium}=require('playwright');
fs.mkdirSync('output',{recursive:true});
const root=path.resolve(__dirname,'../site');
const server=http.createServer((req,res)=>{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root)){res.statusCode=403;return res.end();}if(req.url.startsWith('/fixture')){let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<script type="module" src="host.js[^"]*"><\/script>/,'');res.setHeader('Content-Type','text/html');return res.end(html);}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.png')?'image/png':'text/plain');let data=fs.readFileSync(file);if(file.endsWith('addin.js'))data=data.toString().replace(/^import .*;$/m,'');res.end(data);}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const page=await browser.newPage({viewport:{width:420,height:820}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${port}/fixture`);await page.waitForFunction(()=>!!window.__lesson);await page.evaluate(()=>{const L=window.__lesson,S=L.S;S.role='student';S.joined=true;S.connected=true;S.me={name:'Student',key:'me'};S.deck={title:'Test lesson',slides:[{id:'q',type:'short',graded:false,title:'Explain your idea'}]};S.deckLoaded=true;S.myAns={q:'My own response'};S.live={code:'ABCDE',slide:0,presenting:false,open:false,tierNames:['A','B','C'],tiers:{}};L.render(true);});assert((await page.locator('#app').innerText()).includes('Waiting for your teacher'));await page.evaluate(()=>{const L=window.__lesson;Object.assign(L.S.live,{presenting:true,open:true,reveal:true,revealKey:{id:'q',key:{accept:['SECRET KEY']}},summary:{rows:[{label:'OTHER RESPONSE',n:1}]}});L.render(true);});const studentText=await page.locator('#app').innerText();assert(!studentText.includes('SECRET KEY'));assert(!studentText.includes('OTHER RESPONSE'));assert.equal(await page.locator('input[id^="s-ans"]').inputValue(),'My own response');await page.screenshot({path:'output/student-nour-preview.png'});
await page.evaluate(async()=>{const L=window.__lesson,S=L.S;S.role='teacher';S.live={slide:0,code:'ABCDE',open:false,presenting:false,reveal:false,sessionId:'s',tierNames:['A','B','C'],thresholds:[50,80]};S.keys={};S.respRaw={};S.peers=[];S.db={doc:()=>({set:async()=>{}})};window.EMBED=await import('/addin/taskpane.js');L.render(true);});await page.getByRole('button',{name:'+ Add interaction',exact:true}).click();await page.getByRole('button',{name:/Short answer/}).click();await page.getByLabel('Your question').fill('What did you learn?');assert.equal(await page.getByText('Accepted answers (one per line)').count(),0);assert.equal(await page.getByText('Import slides').count(),0);assert.equal(await page.getByRole('button',{name:'Add to presentation',exact:true}).count(),1);await page.screenshot({path:'output/nour-panel-preview.png'});await page.route('https://appsforoffice.microsoft.com/**',route=>route.fulfill({contentType:'text/javascript',body:''}));
await page.evaluate(async()=>{const L=window.__lesson,S=L.S;S.liveLoaded=true;S.deckLoaded=true;S.deck={title:'Test',slides:[{id:'q',type:'poll',title:'Choose',options:['A','B'],resultsMode:'click',timerSeconds:1}]};S.live={slide:0,code:'ABCDE',presenting:false,open:false,reveal:false,sessionId:'s',tierNames:['A','B','C']};S.keys={};S.respRaw={};window.officeEvents={};window.Office={onReady:async()=>({host:'PowerPoint'}),EventType:{ActiveViewChanged:'active',DocumentSelectionChanged:'selection'},context:{document:{settings:{get:key=>key==='liveLesson'?{mode:'slide',id:'q'}:key==='liveLessonManaged'?true:null},getActiveViewAsync:cb=>cb({status:'succeeded',value:'edit'}),addHandlerAsync:(type,cb)=>window.officeEvents[type]=cb}}};window.EMBED=await import('/addin/addin.js');await window.EMBED.init();L.render(true);});
assert((await page.locator('#app').innerText()).includes('Slide preview'));assert.equal(await page.locator('.bars').count(),0);
await page.evaluate(()=>window.officeEvents.active({activeView:'read'}));await page.waitForFunction(()=>window.__lesson.S.live.presenting&&window.__lesson.S.live.open);assert.equal(await page.locator('.bars').count(),0);
await page.getByRole('button',{name:'Show results',exact:true}).click();assert.equal(await page.locator('.bars').count(),1);assert.equal(await page.evaluate(()=>window.__lesson.S.live.reveal),false);assert.equal(await page.evaluate(()=>window.__lesson.S.live.summary),null);
await page.waitForFunction(()=>!window.__lesson.S.live.open);await page.getByRole("button",{name:"Reopen answers",exact:true}).click();assert.equal(await page.evaluate(()=>window.__lesson.acceptingAnswers(window.__lesson.S.live)),true);await page.evaluate(()=>window.officeEvents.active({activeView:'edit'}));assert.equal(await page.evaluate(()=>window.__lesson.S.live.presenting),false);
assert.deepEqual(errors,[]);console.log('PASS: real browser bootstrap, waiting screen, own-response-only privacy despite legacy payload, no required short-answer key, single-question form, no import, Office edit/read transition, results on click, timer closes answers');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});


